### PR TITLE
Fix eTag caching bug 

### PR DESCRIPTION
**Pull request by davidmcnerney**
Fixes https://github.com/seatgeek/iphone-app/issues/3489

### CODE REVIEW

**Comment by binarylogic** [comment]
Yay :+1:

**Comment by staminajim** [comment]
I was thinking over the weekend that it might be nice to have a global bool on SGHTTPRequest for disabling iOS Etag caching.  You'd generally want it as long as the server is behaving itself - and there's a lot of third parties using SGHTTPRequest.

Thoughts?

**Comment by davidmcnerney** [comment]
Sure seems fine to me, has anyone asked for that?

**Comment by staminajim** [comment]
Nobody has a release with ETag support yet.  This whole problem might go away when our API updates to varnish 4.0 anyway :/  In which case I'd almost prefer to take out these lines.

**Comment by davidmcnerney** [comment]
Which lines would you prefer to take out?

**Comment by binarylogic** [comment]
One thing to note. The HTTP specification does not require `ETag` headers in responses, clients should treat them as optional. As much as I'd like to always guarantee that an `ETag` be present, I think we're better off sticking to the official specification. For instance, assets are served separately from our API calls and therefore might utilize the `Cache-Control` header instead. A really good article on how this works is [here](https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers).

**Comment by staminajim** [comment]
> Which lines would you prefer to take out?

@dallasgutauckis The ones disabling the iOS caching.  Given the black box nature of the iOS caching maybe we can revisit that later (if ever) if we ever find our performance lacking.

@binarylogic SGHTTPRequest will actually respect the cache-control header if it sets an expiry date or tells it to not cache.

**Comment by davidmcnerney** [comment]
I think the code that I added to disable iOS caching needs to stay, otherwise we can have bugs, for the reasons described in the comment in the above commit.

**Pull request merged**
